# Generated by Django 5.0.6 on 2024-06-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_panel.basemodel')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
            bases=('client_panel.basemodel',),
        ),
    ]
