# Generated by Django 5.0.6 on 2024-06-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_booking_video_remove_article_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subkategoriya', 'verbose_name_plural': 'Subkategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='weekarticle',
            options={'verbose_name': 'Haftalik maqola', 'verbose_name_plural': 'Haftalik maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name': 'Hafta', 'verbose_name_plural': 'Haftalar'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Subkategoriya nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeks',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_panel.subcategory', verbose_name='Subkategoriyalar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='content',
            field=models.TextField(verbose_name='Maqola matni'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='weeks/image', verbose_name='Rasm 1'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='weeks/image', verbose_name='Rasm 2'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='video_link',
            field=models.TextField(verbose_name='Video havola'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.weeks', verbose_name='Hafta'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week_description',
            field=models.TextField(verbose_name='Hafta tavsifi'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week_number',
            field=models.IntegerField(unique=True, verbose_name='Hafta raqami'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week_title',
            field=models.CharField(max_length=50, verbose_name='Hafta nomi'),
        ),
    ]
