# Generated by Django 5.0.6 on 2024-06-29 16:30

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_panel.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(max_length=255)),
                ('experiences_detail', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            bases=('client_panel.basemodel',),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_panel.basemodel')),
            ],
            bases=('client_panel.basemodel',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client_panel.basemodel')),
                ('about_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='client_panel.about')),
            ],
            bases=('client_panel.basemodel',),
        ),
    ]
