# Generated by Django 5.0.6 on 2024-06-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0004_alter_subcategory_options_remove_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Manzil', 'verbose_name_plural': 'Manzillar'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Qabulga yozilganlar', 'verbose_name_plural': 'Qabulga yozilganlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Sharh', 'verbose_name_plural': 'Sharhlar'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logolar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefon', 'verbose_name_plural': 'Telefonlar'},
        ),
        migrations.AlterModelOptions(
            name='podcategory',
            options={'verbose_name': 'Podkategoriya', 'verbose_name_plural': 'Podkategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Ijtimoiy tarmoq', 'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subkategoriya', 'verbose_name_plural': 'Subkategoriyalar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='podcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='podcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='weeks',
            name='category',
        ),
        migrations.RemoveField(
            model_name='weeks',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='weeks',
            name='week_description',
        ),
        migrations.AddField(
            model_name='weeks',
            name='image',
            field=models.ImageField(default=1, upload_to='calendar/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.IntegerField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='address',
            name='link',
            field=models.CharField(max_length=50, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.IntegerField(verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(verbose_name="Ko'cha nomi"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Maqola matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pod_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_panel.podcategory', verbose_name='Podkategoriya'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.subcategory', verbose_name='Subkategoriya'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='Video havola'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/image', verbose_name='Banner rasmi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sanasi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='descriptions',
            field=models.TextField(verbose_name="Sharh ta'rif"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(upload_to='comments/photo', verbose_name='Sharh rasmi'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='dark',
            field=models.ImageField(upload_to='logo/image', verbose_name="Logo (qorong'i)"),
        ),
        migrations.AlterField(
            model_name='logo',
            name='light',
            field=models.ImageField(upload_to='logo/image', verbose_name='Logo (yorqin)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions',
            field=models.TextField(verbose_name='Yangilik matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Raqami'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='description',
            field=models.TextField(verbose_name='Podkategoriya tavsifi'),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Podkategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='podcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.subcategory', verbose_name='Subkategoriya'),
        ),
        migrations.AlterField(
            model_name='result',
            name='descriptions',
            field=models.TextField(verbose_name="Natija ta'rif"),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Natija nomi'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.TextField(verbose_name='Ijtimoiy tarmoq havolasi'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ijtimoiy tarmoq nomi'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Subkategoriya nomi'),
        ),
    ]
