# Generated by Django 5.0.6 on 2024-06-29 23:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0005_alter_address_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Qayerlarda ishlaganingizni kiriting')),
            ],
            options={
                'verbose_name': 'Ishlagan joy',
                'verbose_name_plural': 'Ishlagan joylar',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': "Ma'lumotlar", 'verbose_name_plural': "Ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='about',
            name='experiences_detail',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name="Ta'rif"),
        ),
        migrations.AlterField(
            model_name='about',
            name='description1',
            field=models.CharField(max_length=255, verbose_name="Ta'rif 1"),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profession',
            field=models.CharField(max_length=255, verbose_name='Kasbingiz'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=15, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=15, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='certificate/images', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Maqola matni'),
        ),
        migrations.AlterField(
            model_name='weekarticle',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='Video havola'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calendar/images/'),
        ),
    ]
