# Generated by Django 5.0.6 on 2024-06-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0006_experience_alter_about_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pod_category',
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_panel.article', verbose_name='Podkategoriya'),
        ),
    ]
