# Generated by Django 5.0.6 on 2024-06-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0007_remove_article_pod_category_article_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_panel.category', verbose_name='Subkategoriya'),
        ),
    ]
