# Generated by Django 5.0.6 on 2024-06-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0009_alter_article_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.subcategory', verbose_name='Subkategoriya'),
        ),
    ]
