# Generated by Django 5.0.6 on 2024-06-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0010_alter_article_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_link',
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_link1',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Video havola'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_link2',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Video havola'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_link3',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Video havola'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_panel.article', verbose_name="Qaysi maqolaga oid agar yangi maqola bo'lsa bo'sh qolsin "),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.subcategory', verbose_name="Bo'limni tanlang"),
        ),
    ]
