# Generated by Django 5.0.6 on 2024-06-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0012_alter_article_video_link1_alter_article_video_link2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='video_link1',
            new_name='video_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_link2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_link3',
        ),
    ]
