# Generated by Django 5.0.6 on 2024-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0014_comment_title_result_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='name',
        ),
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(default=1, upload_to='logo/image', verbose_name='Social iconini yuklang png holatda'),
            preserve_default=False,
        ),
    ]
