# Generated by Django 5.0.6 on 2024-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0015_remove_address_link_remove_social_name_social_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Tahsil olgan joylarni kiriting')),
            ],
            options={
                'verbose_name': 'Taxsil',
                'verbose_name_plural': 'Tahsil olgan joylar',
            },
        ),
        migrations.CreateModel(
            name='EducationPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Malaka olgan joylarni kiriting')),
            ],
            options={
                'verbose_name': 'Malaka',
                'verbose_name_plural': 'Malaka olgan joylar',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
