# Generated by Django 5.0.6 on 2024-07-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0016_education_educationpro_remove_about_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='educationpro',
            old_name='description',
            new_name='text',
        ),
    ]
