# Generated by Django 5.0.6 on 2024-07-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0019_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='about/doctor'),
            preserve_default=False,
        ),
    ]
